version: '3.8'
services:
  db:
    container_name: aml-screening-service-db
    image: postgres:14.8-alpine
    restart: always
    environment:
      - POSTGRES_USER=amlservice
      - POSTGRES_PASSWORD=jw8s0F4
      - POSTGRES_DB=amlscreening
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
  app:
    container_name: aml-screening-service
    build:
      dockerfile: Dockerfile
      context: ./
    image: aml-screening-service
    depends_on:
      - db
    ports:
      - 8080:8080
    environment:
      DB_HOST: aml-screening-service-db
      DB_PORT: 5432
      DB_USER: amlservice
      DB_PASSWORD: jw8s0F4
      DB_NAME: amlscreening
    links:
      - db
    volumes:
      - './:/src'
volumes:
  db:
    driver: local