version: '3.8'
services:
  db:
    image: postgres:14.8-alpine
    restart: always
    environment:
      - POSTGRES_USER=amlservice
      - POSTGRES_PASSWORD=jw8s0F4
      - POSTGRES_DB=amlscreening
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local