spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
name: aml-screening-service
enabled: true
server:
  shutdown: graceful

---
spring:
  config:
    activate:
      on-profile: development
name: dev-aml-screening-service
environment: development
enabled: true

