spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
name: aml-screening-service
enabled: true
server:
  shutdown: graceful

---
spring:
  config:
    activate:
      on-profile: development
name: dev-aml-screening-service
environment: development
enabled: true


---
spring:
  config:
    activate:
      on-profile: production
environment: production
enabled: true


