version: 2
jobs:
  build:
    docker:
      - image: cimg/openjdk:17.0.7-node

    working_directory: ~/aml-screening-service

    steps:
      # git pull
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - aml-screening-service-{{ checksum "pom.xml" }}

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: aml-screening-service-{{ checksum "pom.xml" }}

      # build
      - run: mvn clean compile
  test:
    docker:
      - image: cimg/openjdk:17.0.7-node

    working_directory: ~/aml-screening-service
    steps:
      # Verify
      - run: mvn verify

      # store test results
      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always
      - store_test_results:
          path: ~/test-results
  package:
    docker:
      - image: cimg/openjdk:17.0.7-node

    working_directory: ~/aml-screening-service
    steps:

    # package into a jar
    - run: mvn clean package

    # store raw contents of src code
    - store_artifacts:
        path: target/classes
        destination: aml-screening-service

workflows:
  build-workflow:
    jobs:
      - build
      - test
      - package